version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DATABASE-URL: ${TESTING_DB}
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules
  postgres:
    image: postgres:latest
    ports:
      - "8100:3000"
    environment:
      POSTGRES_USER: ${DB-USERNAME}
      POSTGRES_PASSWORD: ${DB-PASSWORD}
      POSTGRES_DB: ${DATABASE-URL}